### ISSUE TITLE
when checking the repository I get an SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by joyshmitz** [seapath/repo-manifest#3]
```bash
❯ repo init -u ssh://github.com/seapath/repo-manifest.git
Get https://gerrit.googlesource.com/git-repo/clone.bundle
Get https://gerrit.googlesource.com/git-repo
remote: Counting objects: 1, done
remote: Finding sources: 100% (41/41)
remote: Total 41 (delta 15), reused 41 (delta 15)
Unpacking objects: 100% (41/41), done.
From https://gerrit.googlesource.com/git-repo
   5d58c18..5ba2120  main       -> origin/main
 * [new tag]         v2.15.4    -> v2.15.4
  File "/home/sd/github/seapath/.repo/repo/main.py", line 79
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
```
OS:
# cat /etc/*release*

```bash
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
...
```

```bash
#  /usr/bin/env python 
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
```

after change python to 3.7

```bash
# update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2
```

have next error

```bash
repo init -u ssh://github.com/seapath/repo-manifest.git
warning: Python 3 support is currently experimental. YMMV.
Please use Python 2.7 instead.
Traceback (most recent call last):
  File "/usr/bin/repo", line 917, in <module>
    main(sys.argv[1:])
  File "/usr/bin/repo", line 879, in main
    _Init(args, gitc_init=(cmd == 'gitc-init'))
  File "/usr/bin/repo", line 360, in _Init
    _CheckGitVersion()
  File "/usr/bin/repo", line 419, in _CheckGitVersion
    ver_act = ParseGitVersion(ver_str)
  File "/usr/bin/repo", line 389, in ParseGitVersion
    if not ver_str.startswith('git version '):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by insatomcat** [comment]
Sorry for the long wait, I'm just joining the projet.
Is this issue still a problem ?

**Comment by insatomcat** [comment]
Stalled issue, closing.
